New Report Form
WildMeOrg/report-app pull request #37
Opened 2021-01-22 05:07 UTC by degrood21

- Added Custom Field Components (**String**, **Long String**, **Integer**, **Floats**, **Date**, **Date Range**, **Select**, **Multi-Select**, **Lat Long**, **Boolean**, **Area**, **File**, **Location Ids**, **Individual**, **Feet-Meters**) 
- Created temp Settings Packet to test all custom fields listed above 
- Implemented Yup and Formik for form flow and validation to Custom Fields
- Reorganized general form (Title, Location, Photographer, etc) into separate components

Notes:
- Required Fields are denoted by an asterisk -> " * "
- Each step of the form is validated when user presses next button (Will not let user continue if required field is not filled out)
- "_This Field is Required_" will show up in read when validation occurs and user has not filled out the required field

**Tested on both Android and iOS**

<details>
 <summary>Screenshots of Custom Fields in the New Form</summary>
 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 00 33](https://user-images.githubusercontent.com/35583946/105449057-6bb0d700-5c2c-11eb-8508-644d15b53a2e.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 00 55](https://user-images.githubusercontent.com/35583946/105449067-70758b00-5c2c-11eb-8a03-039afa101663.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 01 23](https://user-images.githubusercontent.com/35583946/105449074-74091200-5c2c-11eb-9ea9-3c265dd068b7.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 01 37](https://user-images.githubusercontent.com/35583946/105449080-79665c80-5c2c-11eb-818f-a144a77a9054.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 01 39](https://user-images.githubusercontent.com/35583946/105449086-7d927a00-5c2c-11eb-86de-5b3fdb2251d6.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 21 02 09](https://user-images.githubusercontent.com/35583946/105449092-808d6a80-5c2c-11eb-8e1e-c586375e67d5.png)

</details>

2021-01-28 00:01 UTC, brmscheiner requested changes
Left some comments that need to be addressed, but overall this looks like good progress.

PRs should not be this large, and most of the time they should just be one person's work. For example, each of these things could be a separate PR

- Add LatLong input 
- Add Boolean input
- etc...
- Settings form step 1
- Settings form step 2 
- etc...
- Add formik validation
- Test settings API endpoint

2021-01-28 04:55 UTC, degrood21 commented on src/components/CustomField.jsx
> +    schema != null && schema.label != null ? schema.label : name;
We thought we caught all of our instances of this, definitely working to make that a habit.

2021-01-28 04:57 UTC, degrood21 commented on src/components/NewSightingStackScreen.jsx
> +  const firstPageSchema = yup.object().shape({
Added a card for it in Trello so will be getting that done in this sprint. Easy move.

2021-01-28 04:57 UTC, degrood21 commented on src/components/NewSightingStackScreen.jsx
> +  validationSchema.push(firstPageSchema);
Definitely like this way much better, will be implementing that when we move the schema to the new file.

2021-01-28 04:58 UTC, degrood21 commented on src/components/NewSightingStackScreen.jsx
> +  const getConfig = async () => {
Also added this to Trello, probably best as a hook

2021-01-28 05:01 UTC, degrood21 commented on src/components/Typography.jsx
> +  mergedStyles.push(style);
According to the style docs, arrays are accepted but the only difference is the last style in the array takes precedence. URL: https://reactnative.dev/docs/style . We were having issues with styles as an object with multiple styles, and managed to get arrays working best for multiple styles in our case. Let us know what you think? We can go back and rework it as an object for multiple styles across the project rather than arrays, if need be.

2021-01-28 05:02 UTC, degrood21 commented on src/components/fields/BooleanInput.jsx
> +import { Picker } from '@react-native-community/picker';
Added to the "UI Clean Up" Trello card to get done this sprint

2021-01-28 05:02 UTC, degrood21 commented on src/components/fields/LocationIDInput.jsx
> +          function printChildren(childrenArray, itemArray, depth) {
Referred this to Dylan P as it is his work. I believe he will be presenting it during the code review

2021-01-28 05:03 UTC, degrood21 commented on src/components/fields/MultiSelectInput.jsx
> +  //TODO typeography & validation
Meant to remove these comments, our bad

2021-01-28 05:03 UTC, degrood21 commented on src/components/fields/MultiSelectInput.jsx
> +    });
Always learning something new :)

2021-01-28 05:03 UTC, degrood21 commented on src/constants/sightingFormFields.js
> +export default {
How so?

2021-01-28 05:06 UTC, degrood21 commented
Made changes according to comments above and left comments myself. We apologize for the huge PR, will not happen again. It should have definitely been broken up in many stages.

2021-01-28 19:59 UTC, brmscheiner commented on src/components/fields/MultiSelectInput.jsx
> +  //TODO typeography & validation
no probz

2021-01-28 20:00 UTC, brmscheiner commented on src/components/fields/MultiSelectInput.jsx
> +    });
it took me the longest time to get used to map. but it is definitely the method that improves my code quality the most

2021-01-28 20:01 UTC, brmscheiner commented
@degrood21 sounds good no worries. this is a learning process! just let me know when to recheck

2021-01-29 00:27 UTC, degrood21 commented on src/constants/sightingFormFields.js
> +export default {
Went back and realized the numbers are not used anymore so what is left is only the names

2021-01-29 00:30 UTC, degrood21 commented
Added Trello card for Boolean component change request, moving validation schemas to separate file, and getConfig function as a hook in a sep file. Those will be done as separate PR's in this sprint.

I also left a followup regarding your comment on the text input accepting a style object and not an array. Ashika and I also addressed the "feels wrong" comment about the keys as names and numbers. Indeed your feeling was correct, and the file only needed the names as keys. 

Other than that, a recheck would be appreciated and hopefully an approval! Thank you!

2021-01-29 21:39 UTC, brmscheiner commented on src/components/LabeledInput.jsx
> +      : displayType;
code still looks the same as it did i think

2021-01-29 21:41 UTC, brmscheiner commented on src/components/Typography.jsx
> +  mergedStyles.push(style);
Oh nice, I missed that. Since y'all were having issues, it's worth mentioning that all they are doing is applying the spread operator for you.

`[obj1, obj2, obj3]` is turned to into a style object like this:
```
{
 ...obj1,
 ...obj2,
 ...obj3
}
```

2021-01-29 21:43 UTC, brmscheiner approved these changes

2021-01-30 04:18 UTC, merged